#!/bin/bash

ADDRESS="127.0.0.1"
PORT="8000"
PASSWORD="globaleaks"
red="\033[1;31m"
ARGD=0

echo -e "\033[34mWelcome\033[0m \033[1;33mto\033[0m \033[47m\033[34mGloba\033[0m\033[47m\033[30mL\033[0m\033[47m\033[34meaks\033[0m\033[0m"
# When more args are provided: debug mode is enabled
if [ $# -ne "$ARGD" ]
then
    echo -e "${red}log is enabled by default httpserver.log and in globaleaks.conf [logging] section: DO NOT USE IN PRODUCTION\033[0m"
    LOG_OPTION=""

    # optional environmental variable to enhance python debug
    export PYTHONTHREADDEBUG=1
    export PYTHONDUMPREFS=1
    export PYTHONMALLOCSTATS=1
else
    echo -e "${red}you're disabling logging of the webserver, to delete other logs, check the [logging] section in globaleaks.conf"
    echo "to enable log, use [$0 -l]"
    tput sgr0
    LOG_OPTION="-l /dev/null"
fi

FOLDER=$(python -c "import globaleaks, os; print os.path.dirname(globaleaks.__file__)" 2> /dev/null)
if [ ! -z $FOLDER ]; then
    cd $FOLDER
fi

if [ -d "applications/globaleaks/static" ]; then
    echo "cleaning of previously preloaded javascript and css..."
    rm -f applications/globaleaks/static/main_*
fi

python web2py.py -i $ADDRESS -p $PORT -a $PASSWORD $LOG_OPTION
