#!/bin/bash

ADDRESS="127.0.0.1"
PORT="8000"
PASSWORD="globaleaks"
red="\033[1;31m"
ARGD=0

#echo "   _____ _       _           _                 _        ";
#echo "  / ____| |     | |         | |               | |       "
#echo " | |  __| | ___ | |__   __ _| |      ___  __ _| | _____ ";
#echo " | | |_ | |/ _ \| '_ \ / _\` | |     / _ \/ _\` | |/ / __| "
#echo " | |__| | | (_) | |_) | (_| | |____|  __/ (_| |   <\__ \ ";
#echo "  \_____|_|\___/|_.__/ \__,_|______|\___|\__,_|_|\_\___/"
#echo -e "\n\n"

c1="\033[47m\033[34m"

c2="\033[0m"
c3="\033[47m\033[30m"

echo -en "${c1}   _____ _       _          ";echo -en "${c2}${c3} _";echo -e "${c2}${c1}                 _            ${c2}";
echo -en "${c1}  / ____| |     | |         ";echo -en "${c2}${c3}| |";echo -e "${c2}${c1}               | |           ${c2}"
echo -en "${c1} | |  __| | ___ | |__   __ _";echo -en "${c2}${c3}| |";echo -e "${c2}${c1}      ___  __ _| | _____     ${c2}";
echo -en "${c1} | | |_ | |/ _ \| '_ \ / _\` ";echo -en "${c2}${c3}| |";echo -e "${c2}${c1}     / _ \/ _\` | |/ / __|    ${c2}"
echo -en "${c1} | |__| | | (_) | |_) | (_| ";echo -en "${c2}${c3}| |____|";echo -e "${c2}${c1}  __/ (_| |   <\__ \    ${c2}";
echo -en "${c1}  \_____|_|\___/|_.__/ \__,_";echo -en "${c2}${c3}|______|";echo -e "${c2}${c1}\___|\__,_|_|\_\___/    ${c2}"
echo -en "${c1}                                                            ${c2}"
echo -e "\n\n"

echo -e "\033[34mWelcome\033[0m \033[1;33mto\033[0m ${c1}Globa\033[0m\033[47m\033[30mL\033[0m\033[47m\033[34meaks\033[0m\033[0m"
# When more args are provided: debug mode is enabled
if [ $# -ne "$ARGD" ]
then
    echo -e "${red}log is enabled by default httpserver.log and in globaleaks.conf [logging] section: DO NOT USE IN PRODUCTION\033[0m"
    LOG_OPTION=""

    # optional environmental variable to enhance python debug
    export PYTHONTHREADDEBUG=1
    export PYTHONDUMPREFS=1
    export PYTHONMALLOCSTATS=1
else
    echo -e "${red}you're disabling logging of the webserver, to delete other logs, check the [logging] section in globaleaks.conf"
    echo "to enable log, use [$0 -l]"
    tput sgr0
    LOG_OPTION="-l /dev/null"
fi

FOLDER=$(python -c "import globaleaks, os; print os.path.dirname(globaleaks.__file__)" 2> /dev/null)
if [ ! -z $FOLDER ]; then
    cd $FOLDER
fi

if [ -d "applications/globaleaks/static" ]; then
    echo "cleaning of previously preloaded javascript and css..."
    rm -f applications/globaleaks/static/main_*
fi

python web2py.py -i $ADDRESS -p $PORT -a $PASSWORD $LOG_OPTION
